export default [
  {
    path: '/user',
    layout: false,
    routes: [
      { name: '登录', path: '/user/login', component: './User/Login' },
      { path: '/user/settings', name: '个人设置', component: './User/Settings' },
    ],
  },
  { path: '/welcome', name: '', icon: 'smile', component: './Welcome' },
  // { name: '查询表格', icon: 'table', path: '/list', component: './TableList' },
  { path: '/', redirect: '/welcome' },
  { path: '/dongman', name: '动漫', icon: 'smile', component: './VideoList/Dongman/DongmanList' },
  { path: '/player', component: './Player/Player' },
  { path: '/record', name: '', component: './VideoList/Record/Record' },
  { path: '/collection', name: '', component: './User/Collection' },
  {
    path: '/manage',
    name: '',
    access: 'canAdmin',
    icon: 'smile',
    component: './Manage/UploadVideo',
  },
  {
    path: '/guanli',
    name: '信息管理',
    access: 'canAdmin',
    icon: 'smile',
    component: './AllPageFather',
    routes: [
      {
        path: '/guanli',
        redirect: '/guanli/kind',
      },
      { path: '/guanli/kind', name: '动漫类型', component: './Guanli/Kinds/KindManage' },
      { path: '/guanli/series', name: '动漫系列', component: './Guanli/SeriesManagement' },
      { path: '/guanli/test', name: '动漫信息爬虫', component: './Guanli/Test' },
      // { path: '/guanli/test2', name: '测试文件页', component: './Guanli/Test2' },
      // { path: '/guanli/test3', name: '测试文件系列', component: './Guanli/Test3' },
      { path: '/guanli/sensitive', name: '敏感词管理', component: './Guanli/Sensitive' },
      { path: '/guanli/review', name: '举报审核', component: './Guanli/Review' },
    ],
  },
  { path: '*', layout: false, component: './404' },
];
